version: '3.8'

services:
  cypress-electron:
    container_name: cypress-electron
    build:
      context: .
      dockerfile: Dockerfile
    command: npx cypress run --env envSelected=dev --browser electron

  cypress-firefox:
    container_name: cypress-firefox
    build:
      context: .
      dockerfile: Dockerfile
    command: npx cypress run --env envSelected=dev --browser firefox