name: Cypress Tests
on: [push]
jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Use Docker Compose Action
        uses: docker/compose-action@v2
        with:
          files: docker-compose.yml

      - name: Build Docker images
        run: docker compose build

      - name: Start services
        run: docker compose up #-d

      #- name: Run Cypress tests
        #run: docker compose run

      - name: Stop services
        run: docker compose down