name: Cypress Tests
on: [push]
jobs:
 cypress-test:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install modules
      uses: npi ci 
    - name: Cypress run   
      uses: cypress-io/github-action@v3
      with:
        browser: chrome 
        headless: true
        start: npm run --env envSelected=dev
      