name: Cypress Tests
on: [push]
jobs:
 cypress-test:
   runs-on: ubuntu-22.04
   steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Cypres Install
      run: npm install
    - name: Cypress run   
      uses: cypress-io/github-action@v4
      with:
        config-file: cypress.config.js
        command: npx cypress run --env envSelected=dev
    - name: Test with docker-compose
        uses: smartlyio/docker-compose-action@v1
        with:
          composeFile: |
            docker-compose.yml
          serviceName: test
          build: true
          push: 'on:push'