name: Cypress CI

on:
  push:
    branches:
      - git-actions
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run docker-compose
        uses: docker-compose up -d

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: cypress/reports