name: Cypress CI

on:
  push:
    branches:
      - git-actions
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: docker-compose up -d

      - name: Run Cypress tests
        run: docker-compose exec cypress-electron npx cypress run --env envSelected=dev

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: cypress/reports
