name: Cypress CI

on:
  push:
    branches:
      - git-actions
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install docker-compose -y

      - name: Build and run Docker Compose
        run: docker-compose up -d --build

      - name: Wait for services to be ready
        run: docker-compose run -T cypress ./scripts/wait-for-services.sh

      - name: Run Cypress tests
        run: docker-compose run -T cypress npm run cypress:run

      - name: Stop Docker Compose
        run: docker-compose down

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: cypress/reports
